/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FlashRouteImport } from './routes/flash'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as BookCancelRouteImport } from './routes/book.cancel'
import { Route as BookSuccessRouteImport } from './routes/book.success'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioBookingsRouteImport } from './routes/studio.bookings'
import { Route as StudioContentRouteImport } from './routes/studio.content'
import { Route as StudioFlashRouteImport } from './routes/studio.flash'
import { Route as StudioMerchRouteImport } from './routes/studio.merch'
import { Route as StudioPortfolioRouteImport } from './routes/studio.portfolio'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashRoute = FlashRouteImport.update({
  id: '/flash',
  path: '/flash',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const BookCancelRoute = BookCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => BookRoute,
} as any)
const BookSuccessRoute = BookSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BookRoute,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioBookingsRoute = StudioBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => StudioRoute,
} as any)
const StudioContentRoute = StudioContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => StudioRoute,
} as any)
const StudioFlashRoute = StudioFlashRouteImport.update({
  id: '/flash',
  path: '/flash',
  getParentRoute: () => StudioRoute,
} as any)
const StudioMerchRoute = StudioMerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPortfolioRoute = StudioPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => StudioRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRouteWithChildren
  '/contact': typeof ContactRoute
  '/flash': typeof FlashRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/book/cancel': typeof BookCancelRoute
  '/book/success': typeof BookSuccessRoute
  '/studio/bookings': typeof StudioBookingsRoute
  '/studio/content': typeof StudioContentRoute
  '/studio/flash': typeof StudioFlashRoute
  '/studio/merch': typeof StudioMerchRoute
  '/studio/portfolio': typeof StudioPortfolioRoute
  '/studio/': typeof StudioIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRouteWithChildren
  '/contact': typeof ContactRoute
  '/flash': typeof FlashRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/book/cancel': typeof BookCancelRoute
  '/book/success': typeof BookSuccessRoute
  '/studio/bookings': typeof StudioBookingsRoute
  '/studio/content': typeof StudioContentRoute
  '/studio/flash': typeof StudioFlashRoute
  '/studio/merch': typeof StudioMerchRoute
  '/studio/portfolio': typeof StudioPortfolioRoute
  '/studio': typeof StudioIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRouteWithChildren
  '/contact': typeof ContactRoute
  '/flash': typeof FlashRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/book/cancel': typeof BookCancelRoute
  '/book/success': typeof BookSuccessRoute
  '/studio/bookings': typeof StudioBookingsRoute
  '/studio/content': typeof StudioContentRoute
  '/studio/flash': typeof StudioFlashRoute
  '/studio/merch': typeof StudioMerchRoute
  '/studio/portfolio': typeof StudioPortfolioRoute
  '/studio/': typeof StudioIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/book'
    | '/contact'
    | '/flash'
    | '/login'
    | '/merch'
    | '/portfolio'
    | '/sitemap.xml'
    | '/studio'
    | '/book/cancel'
    | '/book/success'
    | '/studio/bookings'
    | '/studio/content'
    | '/studio/flash'
    | '/studio/merch'
    | '/studio/portfolio'
    | '/studio/'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/book'
    | '/contact'
    | '/flash'
    | '/login'
    | '/merch'
    | '/portfolio'
    | '/sitemap.xml'
    | '/book/cancel'
    | '/book/success'
    | '/studio/bookings'
    | '/studio/content'
    | '/studio/flash'
    | '/studio/merch'
    | '/studio/portfolio'
    | '/studio'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/book'
    | '/contact'
    | '/flash'
    | '/login'
    | '/merch'
    | '/portfolio'
    | '/sitemap.xml'
    | '/studio'
    | '/book/cancel'
    | '/book/success'
    | '/studio/bookings'
    | '/studio/content'
    | '/studio/flash'
    | '/studio/merch'
    | '/studio/portfolio'
    | '/studio/'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookRoute: typeof BookRouteWithChildren
  ContactRoute: typeof ContactRoute
  FlashRoute: typeof FlashRoute
  LoginRoute: typeof LoginRoute
  MerchRoute: typeof MerchRoute
  PortfolioRoute: typeof PortfolioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRouteWithChildren
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flash': {
      id: '/flash'
      path: '/flash'
      fullPath: '/flash'
      preLoaderRoute: typeof FlashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/cancel': {
      id: '/book/cancel'
      path: '/cancel'
      fullPath: '/book/cancel'
      preLoaderRoute: typeof BookCancelRouteImport
      parentRoute: typeof BookRoute
    }
    '/book/success': {
      id: '/book/success'
      path: '/success'
      fullPath: '/book/success'
      preLoaderRoute: typeof BookSuccessRouteImport
      parentRoute: typeof BookRoute
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/bookings': {
      id: '/studio/bookings'
      path: '/bookings'
      fullPath: '/studio/bookings'
      preLoaderRoute: typeof StudioBookingsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/content': {
      id: '/studio/content'
      path: '/content'
      fullPath: '/studio/content'
      preLoaderRoute: typeof StudioContentRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/flash': {
      id: '/studio/flash'
      path: '/flash'
      fullPath: '/studio/flash'
      preLoaderRoute: typeof StudioFlashRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/merch': {
      id: '/studio/merch'
      path: '/merch'
      fullPath: '/studio/merch'
      preLoaderRoute: typeof StudioMerchRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/portfolio': {
      id: '/studio/portfolio'
      path: '/portfolio'
      fullPath: '/studio/portfolio'
      preLoaderRoute: typeof StudioPortfolioRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BookRouteChildren {
  BookCancelRoute: typeof BookCancelRoute
  BookSuccessRoute: typeof BookSuccessRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookCancelRoute: BookCancelRoute,
  BookSuccessRoute: BookSuccessRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

interface StudioRouteChildren {
  StudioBookingsRoute: typeof StudioBookingsRoute
  StudioContentRoute: typeof StudioContentRoute
  StudioFlashRoute: typeof StudioFlashRoute
  StudioMerchRoute: typeof StudioMerchRoute
  StudioPortfolioRoute: typeof StudioPortfolioRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioBookingsRoute: StudioBookingsRoute,
  StudioContentRoute: StudioContentRoute,
  StudioFlashRoute: StudioFlashRoute,
  StudioMerchRoute: StudioMerchRoute,
  StudioPortfolioRoute: StudioPortfolioRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookRoute: BookRouteWithChildren,
  ContactRoute: ContactRoute,
  FlashRoute: FlashRoute,
  LoginRoute: LoginRoute,
  MerchRoute: MerchRoute,
  PortfolioRoute: PortfolioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRouteWithChildren,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
